coverage:
  status:
    project:
      default:
        target: 80%
    patch:
      default:
        target: 0%

ignore:
  - "internal/bridgetest"
  - "internal/httprule"
  - "internal/gwquery"
  - "test"
