// source: gotestapi/v1alpha/gotestapi.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = (function() {
  if (this) { return this; }
  if (typeof window !== 'undefined') { return window; }
  if (typeof global !== 'undefined') { return global; }
  if (typeof self !== 'undefined') { return self; }
  return Function('return this')();
}.call(null));

goog.exportSymbol('proto.gotestapi.v1alpha.CreatePurchaseRequest', null, global);
goog.exportSymbol('proto.gotestapi.v1alpha.CreatePurchaseResponse', null, global);
goog.exportSymbol('proto.gotestapi.v1alpha.Veggie', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.gotestapi.v1alpha.CreatePurchaseRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.gotestapi.v1alpha.CreatePurchaseRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.gotestapi.v1alpha.CreatePurchaseRequest.displayName = 'proto.gotestapi.v1alpha.CreatePurchaseRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.gotestapi.v1alpha.CreatePurchaseResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.gotestapi.v1alpha.CreatePurchaseResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.gotestapi.v1alpha.CreatePurchaseResponse.displayName = 'proto.gotestapi.v1alpha.CreatePurchaseResponse';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.gotestapi.v1alpha.CreatePurchaseRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.gotestapi.v1alpha.CreatePurchaseRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.gotestapi.v1alpha.CreatePurchaseRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.gotestapi.v1alpha.CreatePurchaseRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    veggie: jspb.Message.getFieldWithDefault(msg, 1, 0),
    quantity: jspb.Message.getFieldWithDefault(msg, 2, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.gotestapi.v1alpha.CreatePurchaseRequest}
 */
proto.gotestapi.v1alpha.CreatePurchaseRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.gotestapi.v1alpha.CreatePurchaseRequest;
  return proto.gotestapi.v1alpha.CreatePurchaseRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.gotestapi.v1alpha.CreatePurchaseRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.gotestapi.v1alpha.CreatePurchaseRequest}
 */
proto.gotestapi.v1alpha.CreatePurchaseRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.gotestapi.v1alpha.Veggie} */ (reader.readEnum());
      msg.setVeggie(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setQuantity(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.gotestapi.v1alpha.CreatePurchaseRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.gotestapi.v1alpha.CreatePurchaseRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.gotestapi.v1alpha.CreatePurchaseRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.gotestapi.v1alpha.CreatePurchaseRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getVeggie();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getQuantity();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
};


/**
 * optional Veggie veggie = 1;
 * @return {!proto.gotestapi.v1alpha.Veggie}
 */
proto.gotestapi.v1alpha.CreatePurchaseRequest.prototype.getVeggie = function() {
  return /** @type {!proto.gotestapi.v1alpha.Veggie} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.gotestapi.v1alpha.Veggie} value
 * @return {!proto.gotestapi.v1alpha.CreatePurchaseRequest} returns this
 */
proto.gotestapi.v1alpha.CreatePurchaseRequest.prototype.setVeggie = function(value) {
  return jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional int32 quantity = 2;
 * @return {number}
 */
proto.gotestapi.v1alpha.CreatePurchaseRequest.prototype.getQuantity = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.gotestapi.v1alpha.CreatePurchaseRequest} returns this
 */
proto.gotestapi.v1alpha.CreatePurchaseRequest.prototype.setQuantity = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.gotestapi.v1alpha.CreatePurchaseResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.gotestapi.v1alpha.CreatePurchaseResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.gotestapi.v1alpha.CreatePurchaseResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.gotestapi.v1alpha.CreatePurchaseResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    purchaseId: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.gotestapi.v1alpha.CreatePurchaseResponse}
 */
proto.gotestapi.v1alpha.CreatePurchaseResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.gotestapi.v1alpha.CreatePurchaseResponse;
  return proto.gotestapi.v1alpha.CreatePurchaseResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.gotestapi.v1alpha.CreatePurchaseResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.gotestapi.v1alpha.CreatePurchaseResponse}
 */
proto.gotestapi.v1alpha.CreatePurchaseResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setPurchaseId(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.gotestapi.v1alpha.CreatePurchaseResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.gotestapi.v1alpha.CreatePurchaseResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.gotestapi.v1alpha.CreatePurchaseResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.gotestapi.v1alpha.CreatePurchaseResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPurchaseId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string purchase_id = 1;
 * @return {string}
 */
proto.gotestapi.v1alpha.CreatePurchaseResponse.prototype.getPurchaseId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.gotestapi.v1alpha.CreatePurchaseResponse} returns this
 */
proto.gotestapi.v1alpha.CreatePurchaseResponse.prototype.setPurchaseId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * @enum {number}
 */
proto.gotestapi.v1alpha.Veggie = {
  UNKNOWN: 0,
  CARROT: 1,
  TOMATO: 2,
  CUCUMBER: 3,
  POTATO: 4
};

goog.object.extend(exports, proto.gotestapi.v1alpha);
