// source: gotestapi/v1/gotestapi.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = (function() {
  if (this) { return this; }
  if (typeof window !== 'undefined') { return window; }
  if (typeof global !== 'undefined') { return global; }
  if (typeof self !== 'undefined') { return self; }
  return Function('return this')();
}.call(null));

var google_api_annotations_pb = require('../../google/api/annotations_pb.cjs');
goog.object.extend(proto, google_api_annotations_pb);
var gotestapi_v1alpha_gotestapi_pb = require('../../gotestapi/v1alpha/gotestapi_pb.cjs');
goog.object.extend(proto, gotestapi_v1alpha_gotestapi_pb);
goog.exportSymbol('proto.gotestapi.v1.BuildPurchaseRequest', null, global);
goog.exportSymbol('proto.gotestapi.v1.BuildPurchaseRequest.ActionCase', null, global);
goog.exportSymbol('proto.gotestapi.v1.BuildPurchaseResponse', null, global);
goog.exportSymbol('proto.gotestapi.v1.CreateShopRequest', null, global);
goog.exportSymbol('proto.gotestapi.v1.CreateShopResponse', null, global);
goog.exportSymbol('proto.gotestapi.v1.GetStatsRequest', null, global);
goog.exportSymbol('proto.gotestapi.v1.GetStatsResponse', null, global);
goog.exportSymbol('proto.gotestapi.v1.MonitorShopRequest', null, global);
goog.exportSymbol('proto.gotestapi.v1.MonitorShopResponse', null, global);
goog.exportSymbol('proto.gotestapi.v1.MonitorShopResponse.ActionCase', null, global);
goog.exportSymbol('proto.gotestapi.v1.MonitorShopResponse.Purchase', null, global);
goog.exportSymbol('proto.gotestapi.v1.QuantifiedVeggie', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.gotestapi.v1.QuantifiedVeggie = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.gotestapi.v1.QuantifiedVeggie, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.gotestapi.v1.QuantifiedVeggie.displayName = 'proto.gotestapi.v1.QuantifiedVeggie';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.gotestapi.v1.CreateShopRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.gotestapi.v1.CreateShopRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.gotestapi.v1.CreateShopRequest.displayName = 'proto.gotestapi.v1.CreateShopRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.gotestapi.v1.CreateShopResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.gotestapi.v1.CreateShopResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.gotestapi.v1.CreateShopResponse.displayName = 'proto.gotestapi.v1.CreateShopResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.gotestapi.v1.GetStatsRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.gotestapi.v1.GetStatsRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.gotestapi.v1.GetStatsRequest.displayName = 'proto.gotestapi.v1.GetStatsRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.gotestapi.v1.GetStatsResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.gotestapi.v1.GetStatsResponse.repeatedFields_, null);
};
goog.inherits(proto.gotestapi.v1.GetStatsResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.gotestapi.v1.GetStatsResponse.displayName = 'proto.gotestapi.v1.GetStatsResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.gotestapi.v1.BuildPurchaseRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.gotestapi.v1.BuildPurchaseRequest.oneofGroups_);
};
goog.inherits(proto.gotestapi.v1.BuildPurchaseRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.gotestapi.v1.BuildPurchaseRequest.displayName = 'proto.gotestapi.v1.BuildPurchaseRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.gotestapi.v1.BuildPurchaseResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.gotestapi.v1.BuildPurchaseResponse.repeatedFields_, null);
};
goog.inherits(proto.gotestapi.v1.BuildPurchaseResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.gotestapi.v1.BuildPurchaseResponse.displayName = 'proto.gotestapi.v1.BuildPurchaseResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.gotestapi.v1.MonitorShopRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.gotestapi.v1.MonitorShopRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.gotestapi.v1.MonitorShopRequest.displayName = 'proto.gotestapi.v1.MonitorShopRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.gotestapi.v1.MonitorShopResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.gotestapi.v1.MonitorShopResponse.oneofGroups_);
};
goog.inherits(proto.gotestapi.v1.MonitorShopResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.gotestapi.v1.MonitorShopResponse.displayName = 'proto.gotestapi.v1.MonitorShopResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.gotestapi.v1.MonitorShopResponse.Purchase = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.gotestapi.v1.MonitorShopResponse.Purchase.repeatedFields_, null);
};
goog.inherits(proto.gotestapi.v1.MonitorShopResponse.Purchase, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.gotestapi.v1.MonitorShopResponse.Purchase.displayName = 'proto.gotestapi.v1.MonitorShopResponse.Purchase';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.gotestapi.v1.QuantifiedVeggie.prototype.toObject = function(opt_includeInstance) {
  return proto.gotestapi.v1.QuantifiedVeggie.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.gotestapi.v1.QuantifiedVeggie} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.gotestapi.v1.QuantifiedVeggie.toObject = function(includeInstance, msg) {
  var f, obj = {
    veggie: jspb.Message.getFieldWithDefault(msg, 1, 0),
    quantity: jspb.Message.getFieldWithDefault(msg, 2, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.gotestapi.v1.QuantifiedVeggie}
 */
proto.gotestapi.v1.QuantifiedVeggie.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.gotestapi.v1.QuantifiedVeggie;
  return proto.gotestapi.v1.QuantifiedVeggie.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.gotestapi.v1.QuantifiedVeggie} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.gotestapi.v1.QuantifiedVeggie}
 */
proto.gotestapi.v1.QuantifiedVeggie.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.gotestapi.v1alpha.Veggie} */ (reader.readEnum());
      msg.setVeggie(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setQuantity(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.gotestapi.v1.QuantifiedVeggie.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.gotestapi.v1.QuantifiedVeggie.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.gotestapi.v1.QuantifiedVeggie} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.gotestapi.v1.QuantifiedVeggie.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getVeggie();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getQuantity();
  if (f !== 0) {
    writer.writeUint32(
      2,
      f
    );
  }
};


/**
 * optional gotestapi.v1alpha.Veggie veggie = 1;
 * @return {!proto.gotestapi.v1alpha.Veggie}
 */
proto.gotestapi.v1.QuantifiedVeggie.prototype.getVeggie = function() {
  return /** @type {!proto.gotestapi.v1alpha.Veggie} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.gotestapi.v1alpha.Veggie} value
 * @return {!proto.gotestapi.v1.QuantifiedVeggie} returns this
 */
proto.gotestapi.v1.QuantifiedVeggie.prototype.setVeggie = function(value) {
  return jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional uint32 quantity = 2;
 * @return {number}
 */
proto.gotestapi.v1.QuantifiedVeggie.prototype.getQuantity = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.gotestapi.v1.QuantifiedVeggie} returns this
 */
proto.gotestapi.v1.QuantifiedVeggie.prototype.setQuantity = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.gotestapi.v1.CreateShopRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.gotestapi.v1.CreateShopRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.gotestapi.v1.CreateShopRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.gotestapi.v1.CreateShopRequest.toObject = function(includeInstance, msg) {
  var f, obj = {

  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.gotestapi.v1.CreateShopRequest}
 */
proto.gotestapi.v1.CreateShopRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.gotestapi.v1.CreateShopRequest;
  return proto.gotestapi.v1.CreateShopRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.gotestapi.v1.CreateShopRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.gotestapi.v1.CreateShopRequest}
 */
proto.gotestapi.v1.CreateShopRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.gotestapi.v1.CreateShopRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.gotestapi.v1.CreateShopRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.gotestapi.v1.CreateShopRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.gotestapi.v1.CreateShopRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.gotestapi.v1.CreateShopResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.gotestapi.v1.CreateShopResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.gotestapi.v1.CreateShopResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.gotestapi.v1.CreateShopResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    shopId: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.gotestapi.v1.CreateShopResponse}
 */
proto.gotestapi.v1.CreateShopResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.gotestapi.v1.CreateShopResponse;
  return proto.gotestapi.v1.CreateShopResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.gotestapi.v1.CreateShopResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.gotestapi.v1.CreateShopResponse}
 */
proto.gotestapi.v1.CreateShopResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setShopId(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.gotestapi.v1.CreateShopResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.gotestapi.v1.CreateShopResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.gotestapi.v1.CreateShopResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.gotestapi.v1.CreateShopResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getShopId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string shop_id = 1;
 * @return {string}
 */
proto.gotestapi.v1.CreateShopResponse.prototype.getShopId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.gotestapi.v1.CreateShopResponse} returns this
 */
proto.gotestapi.v1.CreateShopResponse.prototype.setShopId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.gotestapi.v1.GetStatsRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.gotestapi.v1.GetStatsRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.gotestapi.v1.GetStatsRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.gotestapi.v1.GetStatsRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    shopId: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.gotestapi.v1.GetStatsRequest}
 */
proto.gotestapi.v1.GetStatsRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.gotestapi.v1.GetStatsRequest;
  return proto.gotestapi.v1.GetStatsRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.gotestapi.v1.GetStatsRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.gotestapi.v1.GetStatsRequest}
 */
proto.gotestapi.v1.GetStatsRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setShopId(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.gotestapi.v1.GetStatsRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.gotestapi.v1.GetStatsRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.gotestapi.v1.GetStatsRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.gotestapi.v1.GetStatsRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getShopId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string shop_id = 1;
 * @return {string}
 */
proto.gotestapi.v1.GetStatsRequest.prototype.getShopId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.gotestapi.v1.GetStatsRequest} returns this
 */
proto.gotestapi.v1.GetStatsRequest.prototype.setShopId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.gotestapi.v1.GetStatsResponse.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.gotestapi.v1.GetStatsResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.gotestapi.v1.GetStatsResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.gotestapi.v1.GetStatsResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.gotestapi.v1.GetStatsResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    purchasedVeggiesList: jspb.Message.toObjectList(msg.getPurchasedVeggiesList(),
    proto.gotestapi.v1.QuantifiedVeggie.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.gotestapi.v1.GetStatsResponse}
 */
proto.gotestapi.v1.GetStatsResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.gotestapi.v1.GetStatsResponse;
  return proto.gotestapi.v1.GetStatsResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.gotestapi.v1.GetStatsResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.gotestapi.v1.GetStatsResponse}
 */
proto.gotestapi.v1.GetStatsResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.gotestapi.v1.QuantifiedVeggie;
      reader.readMessage(value,proto.gotestapi.v1.QuantifiedVeggie.deserializeBinaryFromReader);
      msg.addPurchasedVeggies(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.gotestapi.v1.GetStatsResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.gotestapi.v1.GetStatsResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.gotestapi.v1.GetStatsResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.gotestapi.v1.GetStatsResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPurchasedVeggiesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.gotestapi.v1.QuantifiedVeggie.serializeBinaryToWriter
    );
  }
};


/**
 * repeated QuantifiedVeggie purchased_veggies = 1;
 * @return {!Array<!proto.gotestapi.v1.QuantifiedVeggie>}
 */
proto.gotestapi.v1.GetStatsResponse.prototype.getPurchasedVeggiesList = function() {
  return /** @type{!Array<!proto.gotestapi.v1.QuantifiedVeggie>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.gotestapi.v1.QuantifiedVeggie, 1));
};


/**
 * @param {!Array<!proto.gotestapi.v1.QuantifiedVeggie>} value
 * @return {!proto.gotestapi.v1.GetStatsResponse} returns this
*/
proto.gotestapi.v1.GetStatsResponse.prototype.setPurchasedVeggiesList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.gotestapi.v1.QuantifiedVeggie=} opt_value
 * @param {number=} opt_index
 * @return {!proto.gotestapi.v1.QuantifiedVeggie}
 */
proto.gotestapi.v1.GetStatsResponse.prototype.addPurchasedVeggies = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.gotestapi.v1.QuantifiedVeggie, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.gotestapi.v1.GetStatsResponse} returns this
 */
proto.gotestapi.v1.GetStatsResponse.prototype.clearPurchasedVeggiesList = function() {
  return this.setPurchasedVeggiesList([]);
};



/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.gotestapi.v1.BuildPurchaseRequest.oneofGroups_ = [[2,3]];

/**
 * @enum {number}
 */
proto.gotestapi.v1.BuildPurchaseRequest.ActionCase = {
  ACTION_NOT_SET: 0,
  ADD: 2,
  REMOVE: 3
};

/**
 * @return {proto.gotestapi.v1.BuildPurchaseRequest.ActionCase}
 */
proto.gotestapi.v1.BuildPurchaseRequest.prototype.getActionCase = function() {
  return /** @type {proto.gotestapi.v1.BuildPurchaseRequest.ActionCase} */(jspb.Message.computeOneofCase(this, proto.gotestapi.v1.BuildPurchaseRequest.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.gotestapi.v1.BuildPurchaseRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.gotestapi.v1.BuildPurchaseRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.gotestapi.v1.BuildPurchaseRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.gotestapi.v1.BuildPurchaseRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    shopId: jspb.Message.getFieldWithDefault(msg, 1, ""),
    add: jspb.Message.getFieldWithDefault(msg, 2, 0),
    remove: jspb.Message.getFieldWithDefault(msg, 3, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.gotestapi.v1.BuildPurchaseRequest}
 */
proto.gotestapi.v1.BuildPurchaseRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.gotestapi.v1.BuildPurchaseRequest;
  return proto.gotestapi.v1.BuildPurchaseRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.gotestapi.v1.BuildPurchaseRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.gotestapi.v1.BuildPurchaseRequest}
 */
proto.gotestapi.v1.BuildPurchaseRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setShopId(value);
      break;
    case 2:
      var value = /** @type {!proto.gotestapi.v1alpha.Veggie} */ (reader.readEnum());
      msg.setAdd(value);
      break;
    case 3:
      var value = /** @type {!proto.gotestapi.v1alpha.Veggie} */ (reader.readEnum());
      msg.setRemove(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.gotestapi.v1.BuildPurchaseRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.gotestapi.v1.BuildPurchaseRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.gotestapi.v1.BuildPurchaseRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.gotestapi.v1.BuildPurchaseRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getShopId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = /** @type {!proto.gotestapi.v1alpha.Veggie} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeEnum(
      2,
      f
    );
  }
  f = /** @type {!proto.gotestapi.v1alpha.Veggie} */ (jspb.Message.getField(message, 3));
  if (f != null) {
    writer.writeEnum(
      3,
      f
    );
  }
};


/**
 * optional string shop_id = 1;
 * @return {string}
 */
proto.gotestapi.v1.BuildPurchaseRequest.prototype.getShopId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.gotestapi.v1.BuildPurchaseRequest} returns this
 */
proto.gotestapi.v1.BuildPurchaseRequest.prototype.setShopId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional gotestapi.v1alpha.Veggie add = 2;
 * @return {!proto.gotestapi.v1alpha.Veggie}
 */
proto.gotestapi.v1.BuildPurchaseRequest.prototype.getAdd = function() {
  return /** @type {!proto.gotestapi.v1alpha.Veggie} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {!proto.gotestapi.v1alpha.Veggie} value
 * @return {!proto.gotestapi.v1.BuildPurchaseRequest} returns this
 */
proto.gotestapi.v1.BuildPurchaseRequest.prototype.setAdd = function(value) {
  return jspb.Message.setOneofField(this, 2, proto.gotestapi.v1.BuildPurchaseRequest.oneofGroups_[0], value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.gotestapi.v1.BuildPurchaseRequest} returns this
 */
proto.gotestapi.v1.BuildPurchaseRequest.prototype.clearAdd = function() {
  return jspb.Message.setOneofField(this, 2, proto.gotestapi.v1.BuildPurchaseRequest.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.gotestapi.v1.BuildPurchaseRequest.prototype.hasAdd = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional gotestapi.v1alpha.Veggie remove = 3;
 * @return {!proto.gotestapi.v1alpha.Veggie}
 */
proto.gotestapi.v1.BuildPurchaseRequest.prototype.getRemove = function() {
  return /** @type {!proto.gotestapi.v1alpha.Veggie} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {!proto.gotestapi.v1alpha.Veggie} value
 * @return {!proto.gotestapi.v1.BuildPurchaseRequest} returns this
 */
proto.gotestapi.v1.BuildPurchaseRequest.prototype.setRemove = function(value) {
  return jspb.Message.setOneofField(this, 3, proto.gotestapi.v1.BuildPurchaseRequest.oneofGroups_[0], value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.gotestapi.v1.BuildPurchaseRequest} returns this
 */
proto.gotestapi.v1.BuildPurchaseRequest.prototype.clearRemove = function() {
  return jspb.Message.setOneofField(this, 3, proto.gotestapi.v1.BuildPurchaseRequest.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.gotestapi.v1.BuildPurchaseRequest.prototype.hasRemove = function() {
  return jspb.Message.getField(this, 3) != null;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.gotestapi.v1.BuildPurchaseResponse.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.gotestapi.v1.BuildPurchaseResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.gotestapi.v1.BuildPurchaseResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.gotestapi.v1.BuildPurchaseResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.gotestapi.v1.BuildPurchaseResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    purchasedVeggiesList: jspb.Message.toObjectList(msg.getPurchasedVeggiesList(),
    proto.gotestapi.v1.QuantifiedVeggie.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.gotestapi.v1.BuildPurchaseResponse}
 */
proto.gotestapi.v1.BuildPurchaseResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.gotestapi.v1.BuildPurchaseResponse;
  return proto.gotestapi.v1.BuildPurchaseResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.gotestapi.v1.BuildPurchaseResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.gotestapi.v1.BuildPurchaseResponse}
 */
proto.gotestapi.v1.BuildPurchaseResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.gotestapi.v1.QuantifiedVeggie;
      reader.readMessage(value,proto.gotestapi.v1.QuantifiedVeggie.deserializeBinaryFromReader);
      msg.addPurchasedVeggies(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.gotestapi.v1.BuildPurchaseResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.gotestapi.v1.BuildPurchaseResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.gotestapi.v1.BuildPurchaseResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.gotestapi.v1.BuildPurchaseResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPurchasedVeggiesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.gotestapi.v1.QuantifiedVeggie.serializeBinaryToWriter
    );
  }
};


/**
 * repeated QuantifiedVeggie purchased_veggies = 1;
 * @return {!Array<!proto.gotestapi.v1.QuantifiedVeggie>}
 */
proto.gotestapi.v1.BuildPurchaseResponse.prototype.getPurchasedVeggiesList = function() {
  return /** @type{!Array<!proto.gotestapi.v1.QuantifiedVeggie>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.gotestapi.v1.QuantifiedVeggie, 1));
};


/**
 * @param {!Array<!proto.gotestapi.v1.QuantifiedVeggie>} value
 * @return {!proto.gotestapi.v1.BuildPurchaseResponse} returns this
*/
proto.gotestapi.v1.BuildPurchaseResponse.prototype.setPurchasedVeggiesList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.gotestapi.v1.QuantifiedVeggie=} opt_value
 * @param {number=} opt_index
 * @return {!proto.gotestapi.v1.QuantifiedVeggie}
 */
proto.gotestapi.v1.BuildPurchaseResponse.prototype.addPurchasedVeggies = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.gotestapi.v1.QuantifiedVeggie, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.gotestapi.v1.BuildPurchaseResponse} returns this
 */
proto.gotestapi.v1.BuildPurchaseResponse.prototype.clearPurchasedVeggiesList = function() {
  return this.setPurchasedVeggiesList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.gotestapi.v1.MonitorShopRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.gotestapi.v1.MonitorShopRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.gotestapi.v1.MonitorShopRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.gotestapi.v1.MonitorShopRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    shopId: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.gotestapi.v1.MonitorShopRequest}
 */
proto.gotestapi.v1.MonitorShopRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.gotestapi.v1.MonitorShopRequest;
  return proto.gotestapi.v1.MonitorShopRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.gotestapi.v1.MonitorShopRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.gotestapi.v1.MonitorShopRequest}
 */
proto.gotestapi.v1.MonitorShopRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setShopId(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.gotestapi.v1.MonitorShopRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.gotestapi.v1.MonitorShopRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.gotestapi.v1.MonitorShopRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.gotestapi.v1.MonitorShopRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getShopId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string shop_id = 1;
 * @return {string}
 */
proto.gotestapi.v1.MonitorShopRequest.prototype.getShopId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.gotestapi.v1.MonitorShopRequest} returns this
 */
proto.gotestapi.v1.MonitorShopRequest.prototype.setShopId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};



/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.gotestapi.v1.MonitorShopResponse.oneofGroups_ = [[2,3,4]];

/**
 * @enum {number}
 */
proto.gotestapi.v1.MonitorShopResponse.ActionCase = {
  ACTION_NOT_SET: 0,
  ADD: 2,
  REMOVE: 3,
  PURCHASE: 4
};

/**
 * @return {proto.gotestapi.v1.MonitorShopResponse.ActionCase}
 */
proto.gotestapi.v1.MonitorShopResponse.prototype.getActionCase = function() {
  return /** @type {proto.gotestapi.v1.MonitorShopResponse.ActionCase} */(jspb.Message.computeOneofCase(this, proto.gotestapi.v1.MonitorShopResponse.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.gotestapi.v1.MonitorShopResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.gotestapi.v1.MonitorShopResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.gotestapi.v1.MonitorShopResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.gotestapi.v1.MonitorShopResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    user: jspb.Message.getFieldWithDefault(msg, 1, ""),
    add: jspb.Message.getFieldWithDefault(msg, 2, 0),
    remove: jspb.Message.getFieldWithDefault(msg, 3, 0),
    purchase: (f = msg.getPurchase()) && proto.gotestapi.v1.MonitorShopResponse.Purchase.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.gotestapi.v1.MonitorShopResponse}
 */
proto.gotestapi.v1.MonitorShopResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.gotestapi.v1.MonitorShopResponse;
  return proto.gotestapi.v1.MonitorShopResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.gotestapi.v1.MonitorShopResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.gotestapi.v1.MonitorShopResponse}
 */
proto.gotestapi.v1.MonitorShopResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setUser(value);
      break;
    case 2:
      var value = /** @type {!proto.gotestapi.v1alpha.Veggie} */ (reader.readEnum());
      msg.setAdd(value);
      break;
    case 3:
      var value = /** @type {!proto.gotestapi.v1alpha.Veggie} */ (reader.readEnum());
      msg.setRemove(value);
      break;
    case 4:
      var value = new proto.gotestapi.v1.MonitorShopResponse.Purchase;
      reader.readMessage(value,proto.gotestapi.v1.MonitorShopResponse.Purchase.deserializeBinaryFromReader);
      msg.setPurchase(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.gotestapi.v1.MonitorShopResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.gotestapi.v1.MonitorShopResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.gotestapi.v1.MonitorShopResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.gotestapi.v1.MonitorShopResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getUser();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = /** @type {!proto.gotestapi.v1alpha.Veggie} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeEnum(
      2,
      f
    );
  }
  f = /** @type {!proto.gotestapi.v1alpha.Veggie} */ (jspb.Message.getField(message, 3));
  if (f != null) {
    writer.writeEnum(
      3,
      f
    );
  }
  f = message.getPurchase();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      proto.gotestapi.v1.MonitorShopResponse.Purchase.serializeBinaryToWriter
    );
  }
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.gotestapi.v1.MonitorShopResponse.Purchase.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.gotestapi.v1.MonitorShopResponse.Purchase.prototype.toObject = function(opt_includeInstance) {
  return proto.gotestapi.v1.MonitorShopResponse.Purchase.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.gotestapi.v1.MonitorShopResponse.Purchase} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.gotestapi.v1.MonitorShopResponse.Purchase.toObject = function(includeInstance, msg) {
  var f, obj = {
    veggiesList: jspb.Message.toObjectList(msg.getVeggiesList(),
    proto.gotestapi.v1.QuantifiedVeggie.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.gotestapi.v1.MonitorShopResponse.Purchase}
 */
proto.gotestapi.v1.MonitorShopResponse.Purchase.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.gotestapi.v1.MonitorShopResponse.Purchase;
  return proto.gotestapi.v1.MonitorShopResponse.Purchase.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.gotestapi.v1.MonitorShopResponse.Purchase} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.gotestapi.v1.MonitorShopResponse.Purchase}
 */
proto.gotestapi.v1.MonitorShopResponse.Purchase.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.gotestapi.v1.QuantifiedVeggie;
      reader.readMessage(value,proto.gotestapi.v1.QuantifiedVeggie.deserializeBinaryFromReader);
      msg.addVeggies(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.gotestapi.v1.MonitorShopResponse.Purchase.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.gotestapi.v1.MonitorShopResponse.Purchase.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.gotestapi.v1.MonitorShopResponse.Purchase} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.gotestapi.v1.MonitorShopResponse.Purchase.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getVeggiesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.gotestapi.v1.QuantifiedVeggie.serializeBinaryToWriter
    );
  }
};


/**
 * repeated QuantifiedVeggie veggies = 1;
 * @return {!Array<!proto.gotestapi.v1.QuantifiedVeggie>}
 */
proto.gotestapi.v1.MonitorShopResponse.Purchase.prototype.getVeggiesList = function() {
  return /** @type{!Array<!proto.gotestapi.v1.QuantifiedVeggie>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.gotestapi.v1.QuantifiedVeggie, 1));
};


/**
 * @param {!Array<!proto.gotestapi.v1.QuantifiedVeggie>} value
 * @return {!proto.gotestapi.v1.MonitorShopResponse.Purchase} returns this
*/
proto.gotestapi.v1.MonitorShopResponse.Purchase.prototype.setVeggiesList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.gotestapi.v1.QuantifiedVeggie=} opt_value
 * @param {number=} opt_index
 * @return {!proto.gotestapi.v1.QuantifiedVeggie}
 */
proto.gotestapi.v1.MonitorShopResponse.Purchase.prototype.addVeggies = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.gotestapi.v1.QuantifiedVeggie, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.gotestapi.v1.MonitorShopResponse.Purchase} returns this
 */
proto.gotestapi.v1.MonitorShopResponse.Purchase.prototype.clearVeggiesList = function() {
  return this.setVeggiesList([]);
};


/**
 * optional string user = 1;
 * @return {string}
 */
proto.gotestapi.v1.MonitorShopResponse.prototype.getUser = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.gotestapi.v1.MonitorShopResponse} returns this
 */
proto.gotestapi.v1.MonitorShopResponse.prototype.setUser = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional gotestapi.v1alpha.Veggie add = 2;
 * @return {!proto.gotestapi.v1alpha.Veggie}
 */
proto.gotestapi.v1.MonitorShopResponse.prototype.getAdd = function() {
  return /** @type {!proto.gotestapi.v1alpha.Veggie} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {!proto.gotestapi.v1alpha.Veggie} value
 * @return {!proto.gotestapi.v1.MonitorShopResponse} returns this
 */
proto.gotestapi.v1.MonitorShopResponse.prototype.setAdd = function(value) {
  return jspb.Message.setOneofField(this, 2, proto.gotestapi.v1.MonitorShopResponse.oneofGroups_[0], value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.gotestapi.v1.MonitorShopResponse} returns this
 */
proto.gotestapi.v1.MonitorShopResponse.prototype.clearAdd = function() {
  return jspb.Message.setOneofField(this, 2, proto.gotestapi.v1.MonitorShopResponse.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.gotestapi.v1.MonitorShopResponse.prototype.hasAdd = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional gotestapi.v1alpha.Veggie remove = 3;
 * @return {!proto.gotestapi.v1alpha.Veggie}
 */
proto.gotestapi.v1.MonitorShopResponse.prototype.getRemove = function() {
  return /** @type {!proto.gotestapi.v1alpha.Veggie} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {!proto.gotestapi.v1alpha.Veggie} value
 * @return {!proto.gotestapi.v1.MonitorShopResponse} returns this
 */
proto.gotestapi.v1.MonitorShopResponse.prototype.setRemove = function(value) {
  return jspb.Message.setOneofField(this, 3, proto.gotestapi.v1.MonitorShopResponse.oneofGroups_[0], value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.gotestapi.v1.MonitorShopResponse} returns this
 */
proto.gotestapi.v1.MonitorShopResponse.prototype.clearRemove = function() {
  return jspb.Message.setOneofField(this, 3, proto.gotestapi.v1.MonitorShopResponse.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.gotestapi.v1.MonitorShopResponse.prototype.hasRemove = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional Purchase purchase = 4;
 * @return {?proto.gotestapi.v1.MonitorShopResponse.Purchase}
 */
proto.gotestapi.v1.MonitorShopResponse.prototype.getPurchase = function() {
  return /** @type{?proto.gotestapi.v1.MonitorShopResponse.Purchase} */ (
    jspb.Message.getWrapperField(this, proto.gotestapi.v1.MonitorShopResponse.Purchase, 4));
};


/**
 * @param {?proto.gotestapi.v1.MonitorShopResponse.Purchase|undefined} value
 * @return {!proto.gotestapi.v1.MonitorShopResponse} returns this
*/
proto.gotestapi.v1.MonitorShopResponse.prototype.setPurchase = function(value) {
  return jspb.Message.setOneofWrapperField(this, 4, proto.gotestapi.v1.MonitorShopResponse.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.gotestapi.v1.MonitorShopResponse} returns this
 */
proto.gotestapi.v1.MonitorShopResponse.prototype.clearPurchase = function() {
  return this.setPurchase(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.gotestapi.v1.MonitorShopResponse.prototype.hasPurchase = function() {
  return jspb.Message.getField(this, 4) != null;
};


goog.object.extend(exports, proto.gotestapi.v1);
