// Code generated by "stringer -type=discoveryOrigin -trimprefix=discoveryOrigin"; DO NOT EDIT.

package config

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[discoveryOriginNone-0]
	_ = x[discoveryOriginEnv-1]
	_ = x[discoveryOriginAuto-2]
}

const _discoveryOrigin_name = "NoneEnvAuto"

var _discoveryOrigin_index = [...]uint8{0, 4, 7, 11}

func (i discoveryOrigin) String() string {
	if i < 0 || i >= discoveryOrigin(len(_discoveryOrigin_index)-1) {
		return "discoveryOrigin(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _discoveryOrigin_name[_discoveryOrigin_index[i]:_discoveryOrigin_index[i+1]]
}
